# .golangci.yml

linters:
  disable-all: true
  enable:
    - goimports
    - revive
    - govet
    - unused

linters-settings:
  govet:
    check-shadowing: false
  revive:
    ignore-generated-header: true
  goimports:
    local-prefixes: github.com/kubeshop/testkube

issues:
  exclude-use-default: false
