name: Code build and checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: bitnami/mongodb
        ports:
          - 27017:27017
      nats:
        image: bitnami/nats
        ports:
          - 4222:4222
          - 6222:6222
          - 8222:8222

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Unit test
        run: go test -v ./...

      - name: Integration tests
        run: |
          sudo apt-get install -y git
          go test --tags=integration -v ./...

      # Don't work yet as expected https://github.com/nwestfall/openapi-action/issues/3
      - name: OpenAPI Lint Checks
        uses: nwestfall/openapi-action@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: api/v1/testkube.yaml
